"""Global configuration and constants."""

# Window
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
FPS = 60
TOP_PANEL_HEIGHT = 400
BOTTOM_PANEL_HEIGHT = 400
MENU_BAR_HEIGHT = 44

# Menu layout
MENU_TAB_WIDTH = 110
MENU_TAB_GAP = 8
MENU_LEFT_PAD = 10
MENU_PANEL_WIDTH = 360
MENU_PANEL_PAD = 10
MENU_ROW_HEIGHT = 32

# Landscape
LANDSCAPE_WIDTH = 200
LANDSCAPE_HEIGHT = 200
LANDSCAPE_SCALE = 2  # pixels per landscape cell
WORLD_HEIGHT_CELLS = LANDSCAPE_HEIGHT * 2  # top panel + bottom panel in world units

# Physics
GRAVITY = 30.0
FRICTION_DEFAULT = 0.99  # velocity multiplier per step
BOUNCE_FACTOR_DEFAULT = 0.20  # low initial restitution
BOUNCE_FACTOR_MIN = 0.0
BOUNCE_FACTOR_MAX = 1.0
BOUNCE_FACTOR_STEP = 0.05
VELOCITY_THRESHOLD = 0.03
MAX_STEPS = 1000
DT = 0.016  # 60 fps

# Visualization
COLOR_LANDSCAPE_LOW = (0, 0, 255)  # blue (low score)
COLOR_LANDSCAPE_HIGH = (255, 0, 0)  # red (high score)
COLOR_TARGET = (0, 255, 0)  # green
COLOR_OBSTACLE = (128, 128, 128)  # gray
COLOR_BALL = (255, 255, 0)  # yellow
COLOR_BALL_SETTLED = (255, 255, 255)  # white
BALL_RADIUS_SCREEN = 6
TRAIL_ALPHA = 110
SETTLED_BALL_LINGER_FRAMES = 30
LIVE_SIM_STEPS_PER_FRAME = 4

# Scoring
SCORE_DISTANCE = "distance"
SCORE_TIME = "time"
SCORE_BLEND = "blend"

# Obstacles
OBSTACLE_RADIUS_MIN = 10
OBSTACLE_RADIUS_MAX = 50
OBSTACLE_SIZE_MIN = 15
OBSTACLE_SIZE_MAX = 60
